language: php
php:
- 5.3
- 5.4
- 5.5
- hhvm
env:
  global:
  - secure: wuWvnC0+12oqBxxVyEKoj5ptuOx0m26CvrfXdvQ9yUo/lrpN/Zjcl/r956RxvNryVFb4ig3tDNBRKDUqVD4UuHbB2EFKTUKHZsjSetcQBSO2eQuCcHnvS8zFNRULEFT9fFllUomCWltiOshs3FkTy5tsHnAAxFBy+1zk6GTDx1g=
  - secure: IamfQiU8jvBgkD/53eOK8R/cqqKFx4XAoqsw0n+XaigsZib0QKMWLBeBy0b3qAScgZZHKiG4lOJOUlB8sYbflKQba/1sS3ImIqvrQgN70RT8w+rZMGAQE+emOpvfv4IIxi6NtB9VzPk2eHKikAXLaQ3P9a1z8/YCVX0mREak/4o=
  - secure: I33s7SHgpVEB5LxLch55N9aWExUIbTLoiMpAVMPU208ZwnLpCu9kEN0Azp/NB57b/tSP6YooqzIT5krIhJtegqcZQqV3ru5mTbjPdgMWjBsOfxLLSW5POyiw8mLwpuy1oe3UBHdK/p9tLTCytfPdo5D5h7rzmvQPslVy2FBe9qo=
before_script:
- composer install
after_script:
- php vendor/bin/coveralls
